In [18]:
def experiment(exp_item, seed, groups):
    import hashlib
    import numpy as np
    groups_arr = np.array(groups)
    base = groups_arr.sum()
    m=hashlib.md5(seed+str(exp_item)).hexdigest()[10:]
    small_group = int(m, 16)%base
    return np.searchsorted(np.cumsum(groups)-1, small_group)

##test
import numpy as np
a = np.array([])
for i in range(1,80000):
    a=np.append(a,experiment(i,'test_seed',[1,7,1,1]))


In [21]:
np.mean(a-b)

-0.00063750796884961061

In [23]:
a

array([ 2.,  0.,  0., ...,  2.,  2.,  3.])

In [2]:
np.unique(a, return_counts=True)[1]/float(len(a))

array([ 0.10136377,  0.69894624,  0.10050126,  0.09918874])

In [5]:
np.unique(a, return_counts=True)

(array([ 0.,  1.,  2.,  3.]), array([ 8109, 55915,  8040,  7935], dtype=int64))